spring:
  application:
    name: talkovia
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/talkovia}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
          github:
            client-id: ${CLIENT_ID_GITHUB}
            client-secret: ${CLIENT_SECRET_GITHUB}
#            scope:
#              - profile
#              - email

server:
  servlet:
    context-path: /talkovia
  error:
    include-exception: false

api:
  security:
    token:
      secret: ${TOKEN_SECRET}
